### ISSUE TITLE
nokogiri issue

### ISSUE THREAD

**Issue by brianseehafer** [xssc/gimme-ptc#1]
Getting the following error while running on Win10.  Installed Ruby as well as nokogiri, certified, httpclient, terminal-table, and colorize.   

C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.5-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.5-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from account_creator.rb:1:in `<main>'

Not sure what I'm missing.   Any ideas?

**Comment by xssc** [comment]
did you run `bundle install`

**Comment by brianseehafer** [comment]
Sorry not familiar with Ruby.  Used the installer from RubyInstaller.org then installed the DevKit.  I had no problem installing the gems and ruby -v returns ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by xssc** [comment]
run the commands:

`gem install bundle`

and then

`bundle install`

**Comment by brianseehafer** [comment]
That worked.  Thank you!
