### ISSUE TITLE
Scripts failes to create accounts all time

### ISSUE THREAD

**Issue by Sanafan** [xssc/gimme-ptc#10]
![bildschirmfoto 2016-08-08 um 12 37 28](https://cloud.githubusercontent.com/assets/8384797/17477308/e4684d5c-5d64-11e6-825b-0411d566309d.png)

As you can see, it is not possible to create accounts, or am i doing sth wrong?

**Comment by Sanafan** [comment]
Sorry Guys, i think, this could have caused the issue: 
![bildschirmfoto 2016-08-08 um 12 49 50](https://cloud.githubusercontent.com/assets/8384797/17477625/a6389ddc-5d66-11e6-8ce2-d4ea6e0b9026.png)

**Comment by TachyonRSA** [comment]
Still happening even after the maintenance window.

**Comment by xssc** [comment]
See #3
